//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Accesorios
    {
        
        private Connection conx = new Connection();
        
        public string ACCE_ID { get; set; }
        
        public string ACCE_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryAccesorios()
        {
            return conx.Query("PR_QERYACCESORIOS", null);
        }
        
        public  bool InsertAccesorios(Accesorios obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PACCE_ID", obj.ACCE_ID);
            para[1] = new Parameter("PACCE_NOMBRE", obj.ACCE_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTACCESORIOS", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateAccesorios(Accesorios obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PACCE_ID", obj.ACCE_ID);
            para[1] = new Parameter("PACCE_NOMBRE", obj.ACCE_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTACCESORIOS", para);
            return conx.Transaction(trans);
        }
    }
}
