//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Clausulasempleado
    {
        
        private Connection conx = new Connection();
        
        public string CLAE_ID { get; set; }
        
        public string CLAE_DESCRIPCION { get; set; }
        
        public string CLAE_CONTRATOEMPLEADO { get; set; }
        
        public  System.Data.DataTable QueryClausulasempleado()
        {
            return conx.Query("PR_QERYCLAUSULASEMPLEADO", null);
        }
        
        public  bool InsertClausulasempleado(Clausulasempleado obj)
        {
            Parameter []para = new Parameter[3];
            para[0] = new Parameter("PCLAE_ID", obj.CLAE_ID);
            para[1] = new Parameter("PCLAE_DESCRIPCION", obj.CLAE_DESCRIPCION);
            para[2] = new Parameter("PCLAE_CONTRATOEMPLEADO", obj.CLAE_CONTRATOEMPLEADO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTCLAUSULASEMPLEADO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateClausulasempleado(Clausulasempleado obj)
        {
            Parameter []para = new Parameter[3];
            para[0] = new Parameter("PCLAE_ID", obj.CLAE_ID);
            para[1] = new Parameter("PCLAE_DESCRIPCION", obj.CLAE_DESCRIPCION);
            para[2] = new Parameter("PCLAE_CONTRATOEMPLEADO", obj.CLAE_CONTRATOEMPLEADO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTCLAUSULASEMPLEADO", para);
            return conx.Transaction(trans);
        }
    }
}
