//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Clausulapropietario
    {
        
        private Connection conx = new Connection();
        
        public string CLUP_ID { get; set; }
        
        public string CLUP_CONCEPTO { get; set; }
        
        public string CLUP_CONTRATOPROPIETARIO { get; set; }
        
        public string CONTRATOPROPIETARIO_CONP_ID { get; set; }
        
        public string CLUP_FECHA { get; set; }
        
        public string CLUP_ACTUAL { get; set; }
        
        public string CLUP_NUMERO { get; set; }
        
        public  System.Data.DataTable QueryClausulapropietario()
        {
            return conx.Query("PR_QERYCLAUSULAPROPIETARIO", null);
        }
        
        public  bool InsertClausulapropietario(Clausulapropietario obj)
        {
            Parameter []para = new Parameter[7];
            para[0] = new Parameter("PCLUP_ID", obj.CLUP_ID);
            para[1] = new Parameter("PCLUP_CONCEPTO", obj.CLUP_CONCEPTO);
            para[2] = new Parameter("PCLUP_CONTRATOPROPIETARIO", obj.CLUP_CONTRATOPROPIETARIO);
            para[3] = new Parameter("PCONTRATOPROPIETARIO_CONP_ID", obj.CONTRATOPROPIETARIO_CONP_ID);
            para[4] = new Parameter("PCLUP_FECHA", obj.CLUP_FECHA);
            para[5] = new Parameter("PCLUP_ACTUAL", obj.CLUP_ACTUAL);
            para[6] = new Parameter("PCLUP_NUMERO", obj.CLUP_NUMERO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTCLAUSULAPROPIETARIO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateClausulapropietario(Clausulapropietario obj)
        {
            Parameter []para = new Parameter[7];
            para[0] = new Parameter("PCLUP_ID", obj.CLUP_ID);
            para[1] = new Parameter("PCLUP_CONCEPTO", obj.CLUP_CONCEPTO);
            para[2] = new Parameter("PCLUP_CONTRATOPROPIETARIO", obj.CLUP_CONTRATOPROPIETARIO);
            para[3] = new Parameter("PCONTRATOPROPIETARIO_CONP_ID", obj.CONTRATOPROPIETARIO_CONP_ID);
            para[4] = new Parameter("PCLUP_FECHA", obj.CLUP_FECHA);
            para[5] = new Parameter("PCLUP_ACTUAL", obj.CLUP_ACTUAL);
            para[6] = new Parameter("PCLUP_NUMERO", obj.CLUP_NUMERO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTCLAUSULAPROPIETARIO", para);
            return conx.Transaction(trans);
        }
    }
}
