//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Clausulacliente
    {
        
        private Connection conx = new Connection();
        
        public string CLAC { get; set; }
        
        public string CLAC_DESCRIPCION { get; set; }
        
        public string CONTRATOCLIENTE_CONC { get; set; }
        
        public  System.Data.DataTable QueryClausulacliente()
        {
            return conx.Query("PR_QERYCLAUSULACLIENTE", null);
        }
        
        public  bool InsertClausulacliente(Clausulacliente obj)
        {
            Parameter []para = new Parameter[3];
            para[0] = new Parameter("PCLAC", obj.CLAC);
            para[1] = new Parameter("PCLAC_DESCRIPCION", obj.CLAC_DESCRIPCION);
            para[2] = new Parameter("PCONTRATOCLIENTE_CONC", obj.CONTRATOCLIENTE_CONC);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTCLAUSULACLIENTE", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateClausulacliente(Clausulacliente obj)
        {
            Parameter []para = new Parameter[3];
            para[0] = new Parameter("PCLAC", obj.CLAC);
            para[1] = new Parameter("PCLAC_DESCRIPCION", obj.CLAC_DESCRIPCION);
            para[2] = new Parameter("PCONTRATOCLIENTE_CONC", obj.CONTRATOCLIENTE_CONC);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTCLAUSULACLIENTE", para);
            return conx.Transaction(trans);
        }
    }
}
