//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Cliente
    {
        
        private Connection conx = new Connection();
        
        public string CLIE_ID { get; set; }
        
        public string CLIE_NOMBRES { get; set; }
        
        public string TIPOCLIENTE_TIPC_ID { get; set; }
        
        public string TIPOPERSONA_TIPP_ID { get; set; }
        
        public string CLIE_APELLIDOS { get; set; }
        
        public string CLIE_DIRECCION { get; set; }
        
        public string CLIE_TELEFONO { get; set; }
        
        public string CLIE_TIPODOCUMENTO { get; set; }
        
        public  System.Data.DataTable QueryCliente()
        {
            return conx.Query("PR_QERYCLIENTE", null);
        }
        
        public  bool InsertCliente(Cliente obj)
        {
            Parameter []para = new Parameter[8];
            para[0] = new Parameter("PCLIE_ID", obj.CLIE_ID);
            para[1] = new Parameter("PCLIE_NOMBRES", obj.CLIE_NOMBRES);
            para[2] = new Parameter("PTIPOCLIENTE_TIPC_ID", obj.TIPOCLIENTE_TIPC_ID);
            para[3] = new Parameter("PTIPOPERSONA_TIPP_ID", obj.TIPOPERSONA_TIPP_ID);
            para[4] = new Parameter("PCLIE_APELLIDOS", obj.CLIE_APELLIDOS);
            para[5] = new Parameter("PCLIE_DIRECCION", obj.CLIE_DIRECCION);
            para[6] = new Parameter("PCLIE_TELEFONO", obj.CLIE_TELEFONO);
            para[7] = new Parameter("PCLIE_TIPODOCUMENTO", obj.CLIE_TIPODOCUMENTO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTCLIENTE", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateCliente(Cliente obj)
        {
            Parameter []para = new Parameter[8];
            para[0] = new Parameter("PCLIE_ID", obj.CLIE_ID);
            para[1] = new Parameter("PCLIE_NOMBRES", obj.CLIE_NOMBRES);
            para[2] = new Parameter("PTIPOCLIENTE_TIPC_ID", obj.TIPOCLIENTE_TIPC_ID);
            para[3] = new Parameter("PTIPOPERSONA_TIPP_ID", obj.TIPOPERSONA_TIPP_ID);
            para[4] = new Parameter("PCLIE_APELLIDOS", obj.CLIE_APELLIDOS);
            para[5] = new Parameter("PCLIE_DIRECCION", obj.CLIE_DIRECCION);
            para[6] = new Parameter("PCLIE_TELEFONO", obj.CLIE_TELEFONO);
            para[7] = new Parameter("PCLIE_TIPODOCUMENTO", obj.CLIE_TIPODOCUMENTO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTCLIENTE", para);
            return conx.Transaction(trans);
        }
    }
}
