//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Conceptomantenimiento
    {
        
        private Connection conx = new Connection();
        
        public string CONM_ID { get; set; }
        
        public string CONM_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryConceptomantenimiento()
        {
            return conx.Query("PR_QERYCONCEPTOMANTENIMIENTO", null);
        }
        
        public  bool InsertConceptomantenimiento(Conceptomantenimiento obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PCONM_ID", obj.CONM_ID);
            para[1] = new Parameter("PCONM_NOMBRE", obj.CONM_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTCONCEPTOMANTENIMIENTO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateConceptomantenimiento(Conceptomantenimiento obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PCONM_ID", obj.CONM_ID);
            para[1] = new Parameter("PCONM_NOMBRE", obj.CONM_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTCONCEPTOMANTENIMIENTO", para);
            return conx.Transaction(trans);
        }
    }
}
