//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Conceptodescuento
    {
        
        private Connection conx = new Connection();
        
        public string COND_ID { get; set; }
        
        public string COND_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryConceptodescuento()
        {
            return conx.Query("PR_QERYCONCEPTODESCUENTO", null);
        }
        
        public  bool InsertConceptodescuento(Conceptodescuento obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PCOND_ID", obj.COND_ID);
            para[1] = new Parameter("PCOND_NOMBRE", obj.COND_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTCONCEPTODESCUENTO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateConceptodescuento(Conceptodescuento obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PCOND_ID", obj.COND_ID);
            para[1] = new Parameter("PCOND_NOMBRE", obj.COND_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTCONCEPTODESCUENTO", para);
            return conx.Transaction(trans);
        }
    }
}
