//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Contratopropietario
    {
        
        private Connection conx = new Connection();
        
        public string CONP_ID { get; set; }
        
        public string CONP_FECHA_INICIO { get; set; }
        
        public string CONP_FECHA_FIN { get; set; }
        
        public string CONP_VALOR_PERIODO { get; set; }
        
        public string CONP_VALOR_TOTAL { get; set; }
        
        public string CONP_PERIODOPAGO { get; set; }
        
        public string CONP_ESTADO { get; set; }
        
        public string CONP_SUCURSALEMPRESA { get; set; }
        
        public string CONP_PROPIETARIOVEHICULO { get; set; }
        
        public  System.Data.DataTable QueryContratopropietario()
        {
            return conx.Query("PR_QERYCONTRATOPROPIETARIO", null);
        }
        
        public  bool InsertContratopropietario(Contratopropietario obj)
        {
            Parameter []para = new Parameter[9];
            para[0] = new Parameter("PCONP_ID", obj.CONP_ID);
            para[1] = new Parameter("PCONP_FECHA_INICIO", obj.CONP_FECHA_INICIO);
            para[2] = new Parameter("PCONP_FECHA_FIN", obj.CONP_FECHA_FIN);
            para[3] = new Parameter("PCONP_VALOR_PERIODO", obj.CONP_VALOR_PERIODO);
            para[4] = new Parameter("PCONP_VALOR_TOTAL", obj.CONP_VALOR_TOTAL);
            para[5] = new Parameter("PCONP_PERIODOPAGO", obj.CONP_PERIODOPAGO);
            para[6] = new Parameter("PCONP_ESTADO", obj.CONP_ESTADO);
            para[7] = new Parameter("PCONP_SUCURSALEMPRESA", obj.CONP_SUCURSALEMPRESA);
            para[8] = new Parameter("PCONP_PROPIETARIOVEHICULO", obj.CONP_PROPIETARIOVEHICULO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTCONTRATOPROPIETARIO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateContratopropietario(Contratopropietario obj)
        {
            Parameter []para = new Parameter[9];
            para[0] = new Parameter("PCONP_ID", obj.CONP_ID);
            para[1] = new Parameter("PCONP_FECHA_INICIO", obj.CONP_FECHA_INICIO);
            para[2] = new Parameter("PCONP_FECHA_FIN", obj.CONP_FECHA_FIN);
            para[3] = new Parameter("PCONP_VALOR_PERIODO", obj.CONP_VALOR_PERIODO);
            para[4] = new Parameter("PCONP_VALOR_TOTAL", obj.CONP_VALOR_TOTAL);
            para[5] = new Parameter("PCONP_PERIODOPAGO", obj.CONP_PERIODOPAGO);
            para[6] = new Parameter("PCONP_ESTADO", obj.CONP_ESTADO);
            para[7] = new Parameter("PCONP_SUCURSALEMPRESA", obj.CONP_SUCURSALEMPRESA);
            para[8] = new Parameter("PCONP_PROPIETARIOVEHICULO", obj.CONP_PROPIETARIOVEHICULO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTCONTRATOPROPIETARIO", para);
            return conx.Transaction(trans);
        }
    }
}
