//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Contratoempleado
    {
        
        private Connection conx = new Connection();
        
        public string CONE_SUCURSALEMPRESA { get; set; }
        
        public string CONE_EMPLEADO { get; set; }
        
        public string CONE_DESCRIPCION { get; set; }
        
        public string CONE_SOPORTE { get; set; }
        
        public string CONE_ID { get; set; }
        
        public string CONE_TIPOCONTRATO { get; set; }
        
        public string CONE_PAGOPERIODO { get; set; }
        
        public string CONE_PAGO { get; set; }
        
        public string CONE_PAGOTOTAL { get; set; }
        
        public  System.Data.DataTable QueryContratoempleado()
        {
            return conx.Query("PR_QERYCONTRATOEMPLEADO", null);
        }
        
        public  bool InsertContratoempleado(Contratoempleado obj)
        {
            Parameter []para = new Parameter[9];
            para[0] = new Parameter("PCONE_SUCURSALEMPRESA", obj.CONE_SUCURSALEMPRESA);
            para[1] = new Parameter("PCONE_EMPLEADO", obj.CONE_EMPLEADO);
            para[2] = new Parameter("PCONE_DESCRIPCION", obj.CONE_DESCRIPCION);
            para[3] = new Parameter("PCONE_SOPORTE", obj.CONE_SOPORTE);
            para[4] = new Parameter("PCONE_ID", obj.CONE_ID);
            para[5] = new Parameter("PCONE_TIPOCONTRATO", obj.CONE_TIPOCONTRATO);
            para[6] = new Parameter("PCONE_PAGOPERIODO", obj.CONE_PAGOPERIODO);
            para[7] = new Parameter("PCONE_PAGO", obj.CONE_PAGO);
            para[8] = new Parameter("PCONE_PAGOTOTAL", obj.CONE_PAGOTOTAL);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTCONTRATOEMPLEADO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateContratoempleado(Contratoempleado obj)
        {
            Parameter []para = new Parameter[9];
            para[0] = new Parameter("PCONE_SUCURSALEMPRESA", obj.CONE_SUCURSALEMPRESA);
            para[1] = new Parameter("PCONE_EMPLEADO", obj.CONE_EMPLEADO);
            para[2] = new Parameter("PCONE_DESCRIPCION", obj.CONE_DESCRIPCION);
            para[3] = new Parameter("PCONE_SOPORTE", obj.CONE_SOPORTE);
            para[4] = new Parameter("PCONE_ID", obj.CONE_ID);
            para[5] = new Parameter("PCONE_TIPOCONTRATO", obj.CONE_TIPOCONTRATO);
            para[6] = new Parameter("PCONE_PAGOPERIODO", obj.CONE_PAGOPERIODO);
            para[7] = new Parameter("PCONE_PAGO", obj.CONE_PAGO);
            para[8] = new Parameter("PCONE_PAGOTOTAL", obj.CONE_PAGOTOTAL);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTCONTRATOEMPLEADO", para);
            return conx.Transaction(trans);
        }
    }
}
