//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Contratocliente
    {
        
        private Connection conx = new Connection();
        
        public string CONC { get; set; }
        
        public string CONC_FECHA_INICIO { get; set; }
        
        public string CONC_FECHA_FIN { get; set; }
        
        public string CONC_DESCRIPCION { get; set; }
        
        public string CONC_VALOR { get; set; }
        
        public string CONC_CLIENTE { get; set; }
        
        public string CONC_PROPIETARIOVEHICULO { get; set; }
        
        public string CONC_AFILIADOR { get; set; }
        
        public string CONC_SOPORTE { get; set; }
        
        public string CONC_CONDUCTOR { get; set; }
        
        public  System.Data.DataTable QueryContratocliente()
        {
            return conx.Query("PR_QERYCONTRATOCLIENTE", null);
        }
        
        public  bool InsertContratocliente(Contratocliente obj)
        {
            Parameter []para = new Parameter[10];
            para[0] = new Parameter("PCONC", obj.CONC);
            para[1] = new Parameter("PCONC_FECHA_INICIO", obj.CONC_FECHA_INICIO);
            para[2] = new Parameter("PCONC_FECHA_FIN", obj.CONC_FECHA_FIN);
            para[3] = new Parameter("PCONC_DESCRIPCION", obj.CONC_DESCRIPCION);
            para[4] = new Parameter("PCONC_VALOR", obj.CONC_VALOR);
            para[5] = new Parameter("PCONC_CLIENTE", obj.CONC_CLIENTE);
            para[6] = new Parameter("PCONC_PROPIETARIOVEHICULO", obj.CONC_PROPIETARIOVEHICULO);
            para[7] = new Parameter("PCONC_AFILIADOR", obj.CONC_AFILIADOR);
            para[8] = new Parameter("PCONC_SOPORTE", obj.CONC_SOPORTE);
            para[9] = new Parameter("PCONC_CONDUCTOR", obj.CONC_CONDUCTOR);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTCONTRATOCLIENTE", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateContratocliente(Contratocliente obj)
        {
            Parameter []para = new Parameter[10];
            para[0] = new Parameter("PCONC", obj.CONC);
            para[1] = new Parameter("PCONC_FECHA_INICIO", obj.CONC_FECHA_INICIO);
            para[2] = new Parameter("PCONC_FECHA_FIN", obj.CONC_FECHA_FIN);
            para[3] = new Parameter("PCONC_DESCRIPCION", obj.CONC_DESCRIPCION);
            para[4] = new Parameter("PCONC_VALOR", obj.CONC_VALOR);
            para[5] = new Parameter("PCONC_CLIENTE", obj.CONC_CLIENTE);
            para[6] = new Parameter("PCONC_PROPIETARIOVEHICULO", obj.CONC_PROPIETARIOVEHICULO);
            para[7] = new Parameter("PCONC_AFILIADOR", obj.CONC_AFILIADOR);
            para[8] = new Parameter("PCONC_SOPORTE", obj.CONC_SOPORTE);
            para[9] = new Parameter("PCONC_CONDUCTOR", obj.CONC_CONDUCTOR);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTCONTRATOCLIENTE", para);
            return conx.Transaction(trans);
        }
    }
}
