//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Departamento
    {
        
        private Connection conx = new Connection();
        
        public string DEPA_ID { get; set; }
        
        public string DEPA_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryDepartamento()
        {
            return conx.Query("PR_QERYDEPARTAMENTO", null);
        }
        
        public  bool InsertDepartamento(Departamento obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PDEPA_ID", obj.DEPA_ID);
            para[1] = new Parameter("PDEPA_NOMBRE", obj.DEPA_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTDEPARTAMENTO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateDepartamento(Departamento obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PDEPA_ID", obj.DEPA_ID);
            para[1] = new Parameter("PDEPA_NOMBRE", obj.DEPA_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTDEPARTAMENTO", para);
            return conx.Transaction(trans);
        }
    }
}
