//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Descuento
    {
        
        private Connection conx = new Connection();
        
        public string DESC_ID { get; set; }
        
        public string DESC_VALOR { get; set; }
        
        public string DESC_SOPORTE { get; set; }
        
        public string DESC_DESCONTABLE { get; set; }
        
        public string DESC_PAGO { get; set; }
        
        public string DESC_FECHA { get; set; }
        
        public string DESC_CONCEPTODESCUENTO { get; set; }
        
        public  System.Data.DataTable QueryDescuento()
        {
            return conx.Query("PR_QERYDESCUENTO", null);
        }
        
        public  bool InsertDescuento(Descuento obj)
        {
            Parameter []para = new Parameter[7];
            para[0] = new Parameter("PDESC_ID", obj.DESC_ID);
            para[1] = new Parameter("PDESC_VALOR", obj.DESC_VALOR);
            para[2] = new Parameter("PDESC_SOPORTE", obj.DESC_SOPORTE);
            para[3] = new Parameter("PDESC_DESCONTABLE", obj.DESC_DESCONTABLE);
            para[4] = new Parameter("PDESC_PAGO", obj.DESC_PAGO);
            para[5] = new Parameter("PDESC_FECHA", obj.DESC_FECHA);
            para[6] = new Parameter("PDESC_CONCEPTODESCUENTO", obj.DESC_CONCEPTODESCUENTO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTDESCUENTO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateDescuento(Descuento obj)
        {
            Parameter []para = new Parameter[7];
            para[0] = new Parameter("PDESC_ID", obj.DESC_ID);
            para[1] = new Parameter("PDESC_VALOR", obj.DESC_VALOR);
            para[2] = new Parameter("PDESC_SOPORTE", obj.DESC_SOPORTE);
            para[3] = new Parameter("PDESC_DESCONTABLE", obj.DESC_DESCONTABLE);
            para[4] = new Parameter("PDESC_PAGO", obj.DESC_PAGO);
            para[5] = new Parameter("PDESC_FECHA", obj.DESC_FECHA);
            para[6] = new Parameter("PDESC_CONCEPTODESCUENTO", obj.DESC_CONCEPTODESCUENTO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTDESCUENTO", para);
            return conx.Transaction(trans);
        }
    }
}
