//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Detallemantenimiento
    {
        
        private Connection conx = new Connection();
        
        public string DETM_MANTENIMIENTOVEHICULO { get; set; }
        
        public string DETM_TOTAL { get; set; }
        
        public string DETM_CANTIDAD { get; set; }
        
        public string DETM_PRECIO { get; set; }
        
        public string DETM_CONCEPTO { get; set; }
        
        public string DETM_ID { get; set; }
        
        public  System.Data.DataTable QueryDetallemantenimiento()
        {
            return conx.Query("PR_QERYDETALLEMANTENIMIENTO", null);
        }
        
        public  bool InsertDetallemantenimiento(Detallemantenimiento obj)
        {
            Parameter []para = new Parameter[6];
            para[0] = new Parameter("PDETM_MANTENIMIENTOVEHICULO", obj.DETM_MANTENIMIENTOVEHICULO);
            para[1] = new Parameter("PDETM_TOTAL", obj.DETM_TOTAL);
            para[2] = new Parameter("PDETM_CANTIDAD", obj.DETM_CANTIDAD);
            para[3] = new Parameter("PDETM_PRECIO", obj.DETM_PRECIO);
            para[4] = new Parameter("PDETM_CONCEPTO", obj.DETM_CONCEPTO);
            para[5] = new Parameter("PDETM_ID", obj.DETM_ID);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTDETALLEMANTENIMIENTO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateDetallemantenimiento(Detallemantenimiento obj)
        {
            Parameter []para = new Parameter[6];
            para[0] = new Parameter("PDETM_MANTENIMIENTOVEHICULO", obj.DETM_MANTENIMIENTOVEHICULO);
            para[1] = new Parameter("PDETM_TOTAL", obj.DETM_TOTAL);
            para[2] = new Parameter("PDETM_CANTIDAD", obj.DETM_CANTIDAD);
            para[3] = new Parameter("PDETM_PRECIO", obj.DETM_PRECIO);
            para[4] = new Parameter("PDETM_CONCEPTO", obj.DETM_CONCEPTO);
            para[5] = new Parameter("PDETM_ID", obj.DETM_ID);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTDETALLEMANTENIMIENTO", para);
            return conx.Transaction(trans);
        }
    }
}
