//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Empresa
    {
        
        private Connection conx = new Connection();
        
        public string EMPR_NIT { get; set; }
        
        public string EMPR_NOMBRE { get; set; }
        
        public string EMPR_DIRECCION { get; set; }
        
        public string EMPR_FIJO { get; set; }
        
        public string EMPR_CELULAR { get; set; }
        
        public string EMPR_WEB { get; set; }
        
        public string EMPR_EMAIL { get; set; }
        
        public string EMPR_ESLOGAN { get; set; }
        
        public string EMPR_FAVIICON { get; set; }
        
        public string EMPR_ESLOGANIMAGEN { get; set; }
        
        public string EMPR_FECHA_INICIO { get; set; }
        
        public string EMPR_REPRESENTANTE_LEGAL { get; set; }
        
        public  System.Data.DataTable QueryEmpresa()
        {
            return conx.Query("PR_QERYEMPRESA", null);
        }
        
        public  bool InsertEmpresa(Empresa obj)
        {
            Parameter []para = new Parameter[12];
            para[0] = new Parameter("PEMPR_NIT", obj.EMPR_NIT);
            para[1] = new Parameter("PEMPR_NOMBRE", obj.EMPR_NOMBRE);
            para[2] = new Parameter("PEMPR_DIRECCION", obj.EMPR_DIRECCION);
            para[3] = new Parameter("PEMPR_FIJO", obj.EMPR_FIJO);
            para[4] = new Parameter("PEMPR_CELULAR", obj.EMPR_CELULAR);
            para[5] = new Parameter("PEMPR_WEB", obj.EMPR_WEB);
            para[6] = new Parameter("PEMPR_EMAIL", obj.EMPR_EMAIL);
            para[7] = new Parameter("PEMPR_ESLOGAN", obj.EMPR_ESLOGAN);
            para[8] = new Parameter("PEMPR_FAVIICON", obj.EMPR_FAVIICON);
            para[9] = new Parameter("PEMPR_ESLOGANIMAGEN", obj.EMPR_ESLOGANIMAGEN);
            para[10] = new Parameter("PEMPR_FECHA_INICIO", obj.EMPR_FECHA_INICIO);
            para[11] = new Parameter("PEMPR_REPRESENTANTE_LEGAL", obj.EMPR_REPRESENTANTE_LEGAL);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTEMPRESA", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateEmpresa(Empresa obj)
        {
            Parameter []para = new Parameter[12];
            para[0] = new Parameter("PEMPR_NIT", obj.EMPR_NIT);
            para[1] = new Parameter("PEMPR_NOMBRE", obj.EMPR_NOMBRE);
            para[2] = new Parameter("PEMPR_DIRECCION", obj.EMPR_DIRECCION);
            para[3] = new Parameter("PEMPR_FIJO", obj.EMPR_FIJO);
            para[4] = new Parameter("PEMPR_CELULAR", obj.EMPR_CELULAR);
            para[5] = new Parameter("PEMPR_WEB", obj.EMPR_WEB);
            para[6] = new Parameter("PEMPR_EMAIL", obj.EMPR_EMAIL);
            para[7] = new Parameter("PEMPR_ESLOGAN", obj.EMPR_ESLOGAN);
            para[8] = new Parameter("PEMPR_FAVIICON", obj.EMPR_FAVIICON);
            para[9] = new Parameter("PEMPR_ESLOGANIMAGEN", obj.EMPR_ESLOGANIMAGEN);
            para[10] = new Parameter("PEMPR_FECHA_INICIO", obj.EMPR_FECHA_INICIO);
            para[11] = new Parameter("PEMPR_REPRESENTANTE_LEGAL", obj.EMPR_REPRESENTANTE_LEGAL);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTEMPRESA", para);
            return conx.Transaction(trans);
        }
    }
}
