//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Gps
    {
        
        private Connection conx = new Connection();
        
        public string GPS_ID { get; set; }
        
        public string GPS_SISTEMAOPERATIVO { get; set; }
        
        public string GPS_PRECISIÓN { get; set; }
        
        public  System.Data.DataTable QueryGps()
        {
            return conx.Query("PR_QERYGPS", null);
        }
        
        public  bool InsertGps(Gps obj)
        {
            Parameter []para = new Parameter[3];
            para[0] = new Parameter("PGPS_ID", obj.GPS_ID);
            para[1] = new Parameter("PGPS_SISTEMAOPERATIVO", obj.GPS_SISTEMAOPERATIVO);
            para[2] = new Parameter("PGPS_PRECISIÓN", obj.GPS_PRECISIÓN);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTGPS", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateGps(Gps obj)
        {
            Parameter []para = new Parameter[3];
            para[0] = new Parameter("PGPS_ID", obj.GPS_ID);
            para[1] = new Parameter("PGPS_SISTEMAOPERATIVO", obj.GPS_SISTEMAOPERATIVO);
            para[2] = new Parameter("PGPS_PRECISIÓN", obj.GPS_PRECISIÓN);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTGPS", para);
            return conx.Transaction(trans);
        }
    }
}
