//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Mantenimientovehiculo
    {
        
        private Connection conx = new Connection();
        
        public string MANV_VEHILUCO { get; set; }
        
        public string MANV_CONCEPTOMANTENIMIENTO { get; set; }
        
        public string MANV_FECHA { get; set; }
        
        public string MANV_TOTAL { get; set; }
        
        public string MANV_SOPORTE { get; set; }
        
        public string MANV_ID { get; set; }
        
        public string MANV_PROVEEDORMANTENIMIENTO { get; set; }
        
        public string MANV_SUBTOTAL { get; set; }
        
        public string MANV_IVA { get; set; }
        
        public  System.Data.DataTable QueryMantenimientovehiculo()
        {
            return conx.Query("PR_QERYMANTENIMIENTOVEHICULO", null);
        }
        
        public  bool InsertMantenimientovehiculo(Mantenimientovehiculo obj)
        {
            Parameter []para = new Parameter[9];
            para[0] = new Parameter("PMANV_VEHILUCO", obj.MANV_VEHILUCO);
            para[1] = new Parameter("PMANV_CONCEPTOMANTENIMIENTO", obj.MANV_CONCEPTOMANTENIMIENTO);
            para[2] = new Parameter("PMANV_FECHA", obj.MANV_FECHA);
            para[3] = new Parameter("PMANV_TOTAL", obj.MANV_TOTAL);
            para[4] = new Parameter("PMANV_SOPORTE", obj.MANV_SOPORTE);
            para[5] = new Parameter("PMANV_ID", obj.MANV_ID);
            para[6] = new Parameter("PMANV_PROVEEDORMANTENIMIENTO", obj.MANV_PROVEEDORMANTENIMIENTO);
            para[7] = new Parameter("PMANV_SUBTOTAL", obj.MANV_SUBTOTAL);
            para[8] = new Parameter("PMANV_IVA", obj.MANV_IVA);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTMANTENIMIENTOVEHICULO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateMantenimientovehiculo(Mantenimientovehiculo obj)
        {
            Parameter []para = new Parameter[9];
            para[0] = new Parameter("PMANV_VEHILUCO", obj.MANV_VEHILUCO);
            para[1] = new Parameter("PMANV_CONCEPTOMANTENIMIENTO", obj.MANV_CONCEPTOMANTENIMIENTO);
            para[2] = new Parameter("PMANV_FECHA", obj.MANV_FECHA);
            para[3] = new Parameter("PMANV_TOTAL", obj.MANV_TOTAL);
            para[4] = new Parameter("PMANV_SOPORTE", obj.MANV_SOPORTE);
            para[5] = new Parameter("PMANV_ID", obj.MANV_ID);
            para[6] = new Parameter("PMANV_PROVEEDORMANTENIMIENTO", obj.MANV_PROVEEDORMANTENIMIENTO);
            para[7] = new Parameter("PMANV_SUBTOTAL", obj.MANV_SUBTOTAL);
            para[8] = new Parameter("PMANV_IVA", obj.MANV_IVA);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTMANTENIMIENTOVEHICULO", para);
            return conx.Transaction(trans);
        }
    }
}
