//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Marcavehiculo
    {
        
        private Connection conx = new Connection();
        
        public string MARV { get; set; }
        
        public string MARV_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryMarcavehiculo()
        {
            return conx.Query("PR_QERYMARCAVEHICULO", null);
        }
        
        public  bool InsertMarcavehiculo(Marcavehiculo obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PMARV", obj.MARV);
            para[1] = new Parameter("PMARV_NOMBRE", obj.MARV_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTMARCAVEHICULO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateMarcavehiculo(Marcavehiculo obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PMARV", obj.MARV);
            para[1] = new Parameter("PMARV_NOMBRE", obj.MARV_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTMARCAVEHICULO", para);
            return conx.Transaction(trans);
        }
    }
}
