//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Pago
    {
        
        private Connection conx = new Connection();
        
        public string PAGO_ID { get; set; }
        
        public string PAGO_FECHA { get; set; }
        
        public string PAGO_SOPORTE { get; set; }
        
        public string PAGO_CONTRATOPROPIETARIO { get; set; }
        
        public string PAGO_VALOR { get; set; }
        
        public  System.Data.DataTable QueryPago()
        {
            return conx.Query("PR_QERYPAGO", null);
        }
        
        public  bool InsertPago(Pago obj)
        {
            Parameter []para = new Parameter[5];
            para[0] = new Parameter("PPAGO_ID", obj.PAGO_ID);
            para[1] = new Parameter("PPAGO_FECHA", obj.PAGO_FECHA);
            para[2] = new Parameter("PPAGO_SOPORTE", obj.PAGO_SOPORTE);
            para[3] = new Parameter("PPAGO_CONTRATOPROPIETARIO", obj.PAGO_CONTRATOPROPIETARIO);
            para[4] = new Parameter("PPAGO_VALOR", obj.PAGO_VALOR);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTPAGO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdatePago(Pago obj)
        {
            Parameter []para = new Parameter[5];
            para[0] = new Parameter("PPAGO_ID", obj.PAGO_ID);
            para[1] = new Parameter("PPAGO_FECHA", obj.PAGO_FECHA);
            para[2] = new Parameter("PPAGO_SOPORTE", obj.PAGO_SOPORTE);
            para[3] = new Parameter("PPAGO_CONTRATOPROPIETARIO", obj.PAGO_CONTRATOPROPIETARIO);
            para[4] = new Parameter("PPAGO_VALOR", obj.PAGO_VALOR);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTPAGO", para);
            return conx.Transaction(trans);
        }
    }
}
