//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Periodopago
    {
        
        private Connection conx = new Connection();
        
        public string PERP_ID { get; set; }
        
        public string PERP_PERIODO { get; set; }
        
        public  System.Data.DataTable QueryPeriodopago()
        {
            return conx.Query("PR_QERYPERIODOPAGO", null);
        }
        
        public  bool InsertPeriodopago(Periodopago obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PPERP_ID", obj.PERP_ID);
            para[1] = new Parameter("PPERP_PERIODO", obj.PERP_PERIODO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTPERIODOPAGO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdatePeriodopago(Periodopago obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PPERP_ID", obj.PERP_ID);
            para[1] = new Parameter("PPERP_PERIODO", obj.PERP_PERIODO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTPERIODOPAGO", para);
            return conx.Transaction(trans);
        }
    }
}
