//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Poliza
    {
        
        private Connection conx = new Connection();
        
        public string POLI_ID { get; set; }
        
        public string POLI_NOMBRE { get; set; }
        
        public string POLI_FECHA_INICIO { get; set; }
        
        public string POLI_FECHA_FIN { get; set; }
        
        public string POLI_DESCRIPCION { get; set; }
        
        public string POLI_SUCURSALPROVEEDORPOLIZA { get; set; }
        
        public string POLI_SOPORTE { get; set; }
        
        public  System.Data.DataTable QueryPoliza()
        {
            return conx.Query("PR_QERYPOLIZA", null);
        }
        
        public  bool InsertPoliza(Poliza obj)
        {
            Parameter []para = new Parameter[7];
            para[0] = new Parameter("PPOLI_ID", obj.POLI_ID);
            para[1] = new Parameter("PPOLI_NOMBRE", obj.POLI_NOMBRE);
            para[2] = new Parameter("PPOLI_FECHA_INICIO", obj.POLI_FECHA_INICIO);
            para[3] = new Parameter("PPOLI_FECHA_FIN", obj.POLI_FECHA_FIN);
            para[4] = new Parameter("PPOLI_DESCRIPCION", obj.POLI_DESCRIPCION);
            para[5] = new Parameter("PPOLI_SUCURSALPROVEEDORPOLIZA", obj.POLI_SUCURSALPROVEEDORPOLIZA);
            para[6] = new Parameter("PPOLI_SOPORTE", obj.POLI_SOPORTE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTPOLIZA", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdatePoliza(Poliza obj)
        {
            Parameter []para = new Parameter[7];
            para[0] = new Parameter("PPOLI_ID", obj.POLI_ID);
            para[1] = new Parameter("PPOLI_NOMBRE", obj.POLI_NOMBRE);
            para[2] = new Parameter("PPOLI_FECHA_INICIO", obj.POLI_FECHA_INICIO);
            para[3] = new Parameter("PPOLI_FECHA_FIN", obj.POLI_FECHA_FIN);
            para[4] = new Parameter("PPOLI_DESCRIPCION", obj.POLI_DESCRIPCION);
            para[5] = new Parameter("PPOLI_SUCURSALPROVEEDORPOLIZA", obj.POLI_SUCURSALPROVEEDORPOLIZA);
            para[6] = new Parameter("PPOLI_SOPORTE", obj.POLI_SOPORTE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTPOLIZA", para);
            return conx.Transaction(trans);
        }
    }
}
