//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Propietario
    {
        
        private Connection conx = new Connection();
        
        public string PROP_NUMERO { get; set; }
        
        public string PROP_NOMBRES { get; set; }
        
        public string PROP_APELLIDOS { get; set; }
        
        public string PROP_TELEFONO { get; set; }
        
        public string PROP_DIRECCION { get; set; }
        
        public string PROP_NACIMIENTO { get; set; }
        
        public string PROP_GENERO { get; set; }
        
        public string PROP_MUNICIPIO { get; set; }
        
        public string PROP_TIPOPROPIETARIO { get; set; }
        
        public string PROP_TIPODOCUMENTO { get; set; }
        
        public string PROP_EMAIL { get; set; }
        
        public  System.Data.DataTable QueryPropietario()
        {
            return conx.Query("PR_QERYPROPIETARIO", null);
        }
        
        public  bool InsertPropietario(Propietario obj)
        {
            Parameter []para = new Parameter[11];
            para[0] = new Parameter("PPROP_NUMERO", obj.PROP_NUMERO);
            para[1] = new Parameter("PPROP_NOMBRES", obj.PROP_NOMBRES);
            para[2] = new Parameter("PPROP_APELLIDOS", obj.PROP_APELLIDOS);
            para[3] = new Parameter("PPROP_TELEFONO", obj.PROP_TELEFONO);
            para[4] = new Parameter("PPROP_DIRECCION", obj.PROP_DIRECCION);
            para[5] = new Parameter("PPROP_NACIMIENTO", obj.PROP_NACIMIENTO);
            para[6] = new Parameter("PPROP_GENERO", obj.PROP_GENERO);
            para[7] = new Parameter("PPROP_MUNICIPIO", obj.PROP_MUNICIPIO);
            para[8] = new Parameter("PPROP_TIPOPROPIETARIO", obj.PROP_TIPOPROPIETARIO);
            para[9] = new Parameter("PPROP_TIPODOCUMENTO", obj.PROP_TIPODOCUMENTO);
            para[10] = new Parameter("PPROP_EMAIL", obj.PROP_EMAIL);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTPROPIETARIO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdatePropietario(Propietario obj)
        {
            Parameter []para = new Parameter[11];
            para[0] = new Parameter("PPROP_NUMERO", obj.PROP_NUMERO);
            para[1] = new Parameter("PPROP_NOMBRES", obj.PROP_NOMBRES);
            para[2] = new Parameter("PPROP_APELLIDOS", obj.PROP_APELLIDOS);
            para[3] = new Parameter("PPROP_TELEFONO", obj.PROP_TELEFONO);
            para[4] = new Parameter("PPROP_DIRECCION", obj.PROP_DIRECCION);
            para[5] = new Parameter("PPROP_NACIMIENTO", obj.PROP_NACIMIENTO);
            para[6] = new Parameter("PPROP_GENERO", obj.PROP_GENERO);
            para[7] = new Parameter("PPROP_MUNICIPIO", obj.PROP_MUNICIPIO);
            para[8] = new Parameter("PPROP_TIPOPROPIETARIO", obj.PROP_TIPOPROPIETARIO);
            para[9] = new Parameter("PPROP_TIPODOCUMENTO", obj.PROP_TIPODOCUMENTO);
            para[10] = new Parameter("PPROP_EMAIL", obj.PROP_EMAIL);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTPROPIETARIO", para);
            return conx.Transaction(trans);
        }
    }
}
