//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Proveedorpoliza
    {
        
        private Connection conx = new Connection();
        
        public string PROP_ID { get; set; }
        
        public string PROP_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryProveedorpoliza()
        {
            return conx.Query("PR_QERYPROVEEDORPOLIZA", null);
        }
        
        public  bool InsertProveedorpoliza(Proveedorpoliza obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PPROP_ID", obj.PROP_ID);
            para[1] = new Parameter("PPROP_NOMBRE", obj.PROP_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTPROVEEDORPOLIZA", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateProveedorpoliza(Proveedorpoliza obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PPROP_ID", obj.PROP_ID);
            para[1] = new Parameter("PPROP_NOMBRE", obj.PROP_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTPROVEEDORPOLIZA", para);
            return conx.Transaction(trans);
        }
    }
}
