//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Sucursalproveedorpoliza
    {
        
        private Connection conx = new Connection();
        
        public string SUPP_ID { get; set; }
        
        public string SUPP_NOMBRE { get; set; }
        
        public string SUPP_TELEFONO { get; set; }
        
        public string SUPP_DIRECCION { get; set; }
        
        public string PROVEEDORPOLIZA_PROP_ID { get; set; }
        
        public  System.Data.DataTable QuerySucursalproveedorpoliza()
        {
            return conx.Query("PR_QERYSUCURSALPROVEEDORPOLIZA", null);
        }
        
        public  bool InsertSucursalproveedorpoliza(Sucursalproveedorpoliza obj)
        {
            Parameter []para = new Parameter[5];
            para[0] = new Parameter("PSUPP_ID", obj.SUPP_ID);
            para[1] = new Parameter("PSUPP_NOMBRE", obj.SUPP_NOMBRE);
            para[2] = new Parameter("PSUPP_TELEFONO", obj.SUPP_TELEFONO);
            para[3] = new Parameter("PSUPP_DIRECCION", obj.SUPP_DIRECCION);
            para[4] = new Parameter("PPROVEEDORPOLIZA_PROP_ID", obj.PROVEEDORPOLIZA_PROP_ID);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTSUCURSALPROVEEDORPOLIZA", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateSucursalproveedorpoliza(Sucursalproveedorpoliza obj)
        {
            Parameter []para = new Parameter[5];
            para[0] = new Parameter("PSUPP_ID", obj.SUPP_ID);
            para[1] = new Parameter("PSUPP_NOMBRE", obj.SUPP_NOMBRE);
            para[2] = new Parameter("PSUPP_TELEFONO", obj.SUPP_TELEFONO);
            para[3] = new Parameter("PSUPP_DIRECCION", obj.SUPP_DIRECCION);
            para[4] = new Parameter("PPROVEEDORPOLIZA_PROP_ID", obj.PROVEEDORPOLIZA_PROP_ID);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTSUCURSALPROVEEDORPOLIZA", para);
            return conx.Transaction(trans);
        }
    }
}
