//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Sucursalempresa
    {
        
        private Connection conx = new Connection();
        
        public string SUCE_ID { get; set; }
        
        public string SUCE_NOMBRE { get; set; }
        
        public string SUCE_DIRECCION { get; set; }
        
        public string SUCE_TELEFONO { get; set; }
        
        public string SUCE_CORREO { get; set; }
        
        public string EMPRESA_EMPR_NIT { get; set; }
        
        public  System.Data.DataTable QuerySucursalempresa()
        {
            return conx.Query("PR_QERYSUCURSALEMPRESA", null);
        }
        
        public  bool InsertSucursalempresa(Sucursalempresa obj)
        {
            Parameter []para = new Parameter[6];
            para[0] = new Parameter("PSUCE_ID", obj.SUCE_ID);
            para[1] = new Parameter("PSUCE_NOMBRE", obj.SUCE_NOMBRE);
            para[2] = new Parameter("PSUCE_DIRECCION", obj.SUCE_DIRECCION);
            para[3] = new Parameter("PSUCE_TELEFONO", obj.SUCE_TELEFONO);
            para[4] = new Parameter("PSUCE_CORREO", obj.SUCE_CORREO);
            para[5] = new Parameter("PEMPRESA_EMPR_NIT", obj.EMPRESA_EMPR_NIT);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTSUCURSALEMPRESA", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateSucursalempresa(Sucursalempresa obj)
        {
            Parameter []para = new Parameter[6];
            para[0] = new Parameter("PSUCE_ID", obj.SUCE_ID);
            para[1] = new Parameter("PSUCE_NOMBRE", obj.SUCE_NOMBRE);
            para[2] = new Parameter("PSUCE_DIRECCION", obj.SUCE_DIRECCION);
            para[3] = new Parameter("PSUCE_TELEFONO", obj.SUCE_TELEFONO);
            para[4] = new Parameter("PSUCE_CORREO", obj.SUCE_CORREO);
            para[5] = new Parameter("PEMPRESA_EMPR_NIT", obj.EMPRESA_EMPR_NIT);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTSUCURSALEMPRESA", para);
            return conx.Transaction(trans);
        }
    }
}
