//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Tiposangre
    {
        
        private Connection conx = new Connection();
        
        public string TIPS_ID { get; set; }
        
        public string TIPS_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryTiposangre()
        {
            return conx.Query("PR_QERYTIPOSANGRE", null);
        }
        
        public  bool InsertTiposangre(Tiposangre obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPS_ID", obj.TIPS_ID);
            para[1] = new Parameter("PTIPS_NOMBRE", obj.TIPS_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTTIPOSANGRE", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateTiposangre(Tiposangre obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPS_ID", obj.TIPS_ID);
            para[1] = new Parameter("PTIPS_NOMBRE", obj.TIPS_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTTIPOSANGRE", para);
            return conx.Transaction(trans);
        }
    }
}
