//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Tipopersona
    {
        
        private Connection conx = new Connection();
        
        public string TIPP_ID { get; set; }
        
        public string TIPP_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryTipopersona()
        {
            return conx.Query("PR_QERYTIPOPERSONA", null);
        }
        
        public  bool InsertTipopersona(Tipopersona obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPP_ID", obj.TIPP_ID);
            para[1] = new Parameter("PTIPP_NOMBRE", obj.TIPP_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTTIPOPERSONA", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateTipopersona(Tipopersona obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPP_ID", obj.TIPP_ID);
            para[1] = new Parameter("PTIPP_NOMBRE", obj.TIPP_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTTIPOPERSONA", para);
            return conx.Transaction(trans);
        }
    }
}
