//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Tipo_Empleado
    {
        
        private Connection conx = new Connection();
        
        public string TIPE_ID { get; set; }
        
        public string TIPE_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryTipo_Empleado()
        {
            return conx.Query("PR_QERYTIPO_EMPLEADO", null);
        }
        
        public  bool InsertTipo_Empleado(Tipo_Empleado obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPE_ID", obj.TIPE_ID);
            para[1] = new Parameter("PTIPE_NOMBRE", obj.TIPE_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTTIPO_EMPLEADO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateTipo_Empleado(Tipo_Empleado obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPE_ID", obj.TIPE_ID);
            para[1] = new Parameter("PTIPE_NOMBRE", obj.TIPE_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTTIPO_EMPLEADO", para);
            return conx.Transaction(trans);
        }
    }
}
