//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Tipo_Documento
    {
        
        private Connection conx = new Connection();
        
        public string TIPD_ID { get; set; }
        
        public string TIPD_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryTipo_Documento()
        {
            return conx.Query("PR_QERYTIPO_DOCUMENTO", null);
        }
        
        public  bool InsertTipo_Documento(Tipo_Documento obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPD_ID", obj.TIPD_ID);
            para[1] = new Parameter("PTIPD_NOMBRE", obj.TIPD_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTTIPO_DOCUMENTO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateTipo_Documento(Tipo_Documento obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPD_ID", obj.TIPD_ID);
            para[1] = new Parameter("PTIPD_NOMBRE", obj.TIPD_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTTIPO_DOCUMENTO", para);
            return conx.Transaction(trans);
        }
    }
}
