//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Tipovehiculo
    {
        
        private Connection conx = new Connection();
        
        public string TIPV_ID { get; set; }
        
        public string TIPV_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryTipovehiculo()
        {
            return conx.Query("PR_QERYTIPOVEHICULO", null);
        }
        
        public  bool InsertTipovehiculo(Tipovehiculo obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPV_ID", obj.TIPV_ID);
            para[1] = new Parameter("PTIPV_NOMBRE", obj.TIPV_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTTIPOVEHICULO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateTipovehiculo(Tipovehiculo obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPV_ID", obj.TIPV_ID);
            para[1] = new Parameter("PTIPV_NOMBRE", obj.TIPV_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTTIPOVEHICULO", para);
            return conx.Transaction(trans);
        }
    }
}
