//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Tipocontrato
    {
        
        private Connection conx = new Connection();
        
        public string TIPC_ID { get; set; }
        
        public string TIPC_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryTipocontrato()
        {
            return conx.Query("PR_QERYTIPOCONTRATO", null);
        }
        
        public  bool InsertTipocontrato(Tipocontrato obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPC_ID", obj.TIPC_ID);
            para[1] = new Parameter("PTIPC_NOMBRE", obj.TIPC_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTTIPOCONTRATO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateTipocontrato(Tipocontrato obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPC_ID", obj.TIPC_ID);
            para[1] = new Parameter("PTIPC_NOMBRE", obj.TIPC_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTTIPOCONTRATO", para);
            return conx.Transaction(trans);
        }
    }
}
