//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web;
    using GrupoI.Models.UTILITIES;
    
    
    public class Vehiluco
    {
        
        private Connection conx = new Connection();
        
        public string VEHI_PLACA { get; set; }
        
        public string VEHI_MODELO { get; set; }
        
        public string VEHI_TIPOVEHICULO { get; set; }
        
        public string VEHI_COMBUSTIBLE { get; set; }
        
        public string VEHI_CUPO { get; set; }
        
        public string VEHI_CC { get; set; }
        
        public string VEHI_AIREACONDICIONADO { get; set; }
        
        public string VEHI_WIFI { get; set; }
        
        public string VEHI_KILOMETRAJE { get; set; }
        
        public string VEHI_TIPODIRECCION { get; set; }
        
        public string VEHI_TIPOTRANSMISION { get; set; }
        
        public string VEHI_MARCAVEHICULO { get; set; }
        
        public string VEHI_COLORVEHICULO { get; set; }
        
        public string VEHI_GPS { get; set; }
        
        public string VEHI_GPSASIGNADO { get; set; }
        
        public  System.Data.DataTable QueryVehiluco()
        {
            return conx.Query("PR_QERYVEHILUCO", null);
        }
        
        public  bool InsertVehiluco(Vehiluco obj)
        {
            Parameter []para = new Parameter[15];
            para[0] = new Parameter("PVEHI_PLACA", obj.VEHI_PLACA);
            para[1] = new Parameter("PVEHI_MODELO", obj.VEHI_MODELO);
            para[2] = new Parameter("PVEHI_TIPOVEHICULO", obj.VEHI_TIPOVEHICULO);
            para[3] = new Parameter("PVEHI_COMBUSTIBLE", obj.VEHI_COMBUSTIBLE);
            para[4] = new Parameter("PVEHI_CUPO", obj.VEHI_CUPO);
            para[5] = new Parameter("PVEHI_CC", obj.VEHI_CC);
            para[6] = new Parameter("PVEHI_AIREACONDICIONADO", obj.VEHI_AIREACONDICIONADO);
            para[7] = new Parameter("PVEHI_WIFI", obj.VEHI_WIFI);
            para[8] = new Parameter("PVEHI_KILOMETRAJE", obj.VEHI_KILOMETRAJE);
            para[9] = new Parameter("PVEHI_TIPODIRECCION", obj.VEHI_TIPODIRECCION);
            para[10] = new Parameter("PVEHI_TIPOTRANSMISION", obj.VEHI_TIPOTRANSMISION);
            para[11] = new Parameter("PVEHI_MARCAVEHICULO", obj.VEHI_MARCAVEHICULO);
            para[12] = new Parameter("PVEHI_COLORVEHICULO", obj.VEHI_COLORVEHICULO);
            para[13] = new Parameter("PVEHI_GPS", obj.VEHI_GPS);
            para[14] = new Parameter("PVEHI_GPSASIGNADO", obj.VEHI_GPSASIGNADO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTVEHILUCO", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateVehiluco(Vehiluco obj)
        {
            Parameter []para = new Parameter[15];
            para[0] = new Parameter("PVEHI_PLACA", obj.VEHI_PLACA);
            para[1] = new Parameter("PVEHI_MODELO", obj.VEHI_MODELO);
            para[2] = new Parameter("PVEHI_TIPOVEHICULO", obj.VEHI_TIPOVEHICULO);
            para[3] = new Parameter("PVEHI_COMBUSTIBLE", obj.VEHI_COMBUSTIBLE);
            para[4] = new Parameter("PVEHI_CUPO", obj.VEHI_CUPO);
            para[5] = new Parameter("PVEHI_CC", obj.VEHI_CC);
            para[6] = new Parameter("PVEHI_AIREACONDICIONADO", obj.VEHI_AIREACONDICIONADO);
            para[7] = new Parameter("PVEHI_WIFI", obj.VEHI_WIFI);
            para[8] = new Parameter("PVEHI_KILOMETRAJE", obj.VEHI_KILOMETRAJE);
            para[9] = new Parameter("PVEHI_TIPODIRECCION", obj.VEHI_TIPODIRECCION);
            para[10] = new Parameter("PVEHI_TIPOTRANSMISION", obj.VEHI_TIPOTRANSMISION);
            para[11] = new Parameter("PVEHI_MARCAVEHICULO", obj.VEHI_MARCAVEHICULO);
            para[12] = new Parameter("PVEHI_COLORVEHICULO", obj.VEHI_COLORVEHICULO);
            para[13] = new Parameter("PVEHI_GPS", obj.VEHI_GPS);
            para[14] = new Parameter("PVEHI_GPSASIGNADO", obj.VEHI_GPSASIGNADO);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTVEHILUCO", para);
            return conx.Transaction(trans);
        }
    }
}
