//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using ProgramacionIII.Conexion;
    public class tipocombustible
    {
        
        private Connection conx = new Connection();
        
        public string TIPC_ID { get; set; }
        
        public string TIPC_NOMBRE { get; set; }
        
        public  System.Data.DataTable QueryTipocombustible()
        {
            return conx.Query("PR_QERYTIPOCOMBUSTIBLE", null);
        }
        
        public  bool InsertTipocombustible(tipocombustible obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPC_ID", obj.TIPC_ID);
            para[1] = new Parameter("PTIPC_NOMBRE", obj.TIPC_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_NSRTTIPOCOMBUSTIBLE", para);
            return conx.Transaction(trans);
        }
        
        public  bool UpdateTipocombustible(tipocombustible obj)
        {
            Parameter []para = new Parameter[2];
            para[0] = new Parameter("PTIPC_ID", obj.TIPC_ID);
            para[1] = new Parameter("PTIPC_NOMBRE", obj.TIPC_NOMBRE);
            Transaction []trans = new Transaction[1];
            trans[0] = new Transaction("PR_UPDTTIPOCOMBUSTIBLE", para);
            return conx.Transaction(trans);
        }
    }
}
